#!/bin/bash

# I take this script from Anachron's i3blocks
# I only slightly modify this script to add an option to show icon
# I also remove the i3blocks specify script
# To make this works with tint2 executor, polybar custom script, dzen2 feeder, conkybar, lemonbar feeder, dunst notify, etc.
# 'weather -i' = with icon, 'weather' = text only
# Cheers!
# Addy

# Open Weather Map API code, register to http://openweathermap.org to get one ;)
API_KEY="b0d3a0bf99e117a216b6021dbdc070e5"

# Check on http://openweathermap.org/find
CITY_ID="3451138"

ICON_SUNNY="~/.config/conky/lamentis/res/sun-64.png"
ICON_CLOUDY="~/.config/conky/lamentis/res/clouds-64.png"
ICON_RAINY="~/.config/conky/lamentis/res/rain-64.png"
ICON_STORM="~/.config/conky/lamentis/res/storm-64.png"
ICON_SNOW="~/.config/conky/lamentis/res/snow-64.png"
ICON_FOG="~/.config/conky/lamentis/res/dust-64.png"

TEXT_SUNNY="Ensolarado"
TEXT_CLOUDY="Nublado"
TEXT_RAINY="Chuvoso"
TEXT_STORM="Tempestuoso"
TEXT_SNOW="Nevoso"
TEXT_FOG="Neblinoso"

SYMBOL_CELSIUS="˚C"

WEATHER_URL="http://api.openweathermap.org/data/2.5/weather?id=${CITY_ID}&appid=${API_KEY}&units=metric"

WEATHER_INFO=$(wget -qO- "${WEATHER_URL}")
WEATHER_MAIN=$(echo "${WEATHER_INFO}" | grep -o -e '\"main\":\"[a-Z]*\"' | awk -F ':' '{print $2}' | tr -d '"')
WEATHER_TEMP=$(echo "${WEATHER_INFO}" | grep -o -e '\"temp\":\-\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')

if [[ "${WEATHER_MAIN}" = *Snow* ]]; then
	if  [[ $1 = "-i" ]]; then
    echo $ICON_SNOW
    elif  [[ $1 = "-t" ]]; then
    echo "Se for sair, não esqueça de um casaco."
	else
    echo "${TEXT_SNOW} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
	fi
elif [[ "${WEATHER_MAIN}" = *Rain* ]] || [[ "${WEATHER_MAIN}" = *Drizzle* ]]; then
	if  [[ $1 = "-i" ]]; then
    echo $ICON_RAINY
    elif  [[ $1 = "-t" ]]; then
    echo "Se for sair, não esqueça de levar um guarda-chuva"
	else
    echo "${TEXT_RAINY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
	fi
elif [[ "${WEATHER_MAIN}" = *Clouds* ]]; then
	if  [[ $1 = "-i" ]]; then
    echo $ICON_CLOUDY
    elif  [[ $1 = "-t" ]]; then
    echo "Um dia nostálgico"
	else
    echo "${TEXT_CLOUDY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
	fi
elif [[ "${WEATHER_MAIN}" = *Clear* ]]; then
	if  [[ $1 = "-i" ]]; then
    echo $ICON_SUNNY
    elif  [[ $1 = "-t" ]]; then
    echo "Dia perfeito para aproveitar o sol"
	else
    echo "${TEXT_SUNNY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
	fi
elif [[ "${WEATHER_MAIN}" = *Fog* ]] || [[ "${WEATHER_MAIN}" = *Mist* ]]; then
	if  [[ $1 = "-i" ]]; then
    echo $ICON_FOG
    elif  [[ $1 = "-t" ]]; then
    echo "Evite fazer piadas sobre Silent Hill"
	else
    echo "${TEXT_FOG} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
	fi
else
	if  [[ $1 = "-i" ]]; then
    echo ""
    elif  [[ $1 = "-t" ]]; then
    echo "O clima está${WEATHER_MAIN}"
	else
    echo "${WEATHER_MAIN} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
	fi	
fi
